### PR TITLE
[Ocaml] Add an anchor for performance

### PR DESCRIPTION
**Pull request by GuillaumeGen**
This seems to solve the issue mentioned in #162

### CODE REVIEW

**Review by torhovland — APPROVED** [review]
Smallest PR ever 😆

**Comment by GuillaumeGen** [comment]
On my computer, times drop from 
real    1m12,987s
user    1m12,946s
sys     0m0,036s

to
real    0m0,329s
user    0m0,313s
sys     0m0,018s

for the 1024 line case.

**Comment by aspiwack** [comment]
Out of curiosity: why does this PR work?

**Comment by aspiwack** [comment]
Thank you, it's very clear now. It's an easy trap to fall into, I think. A gotcha to keep in mind.

**Comment by GuillaumeGen** [comment]
Just for completeness if anyone finds this issue because it got strike by a similar problem.
Once Nicolas understood that the performance issue stroke us when dealing with a huge pattern matching, I looked for the queries related to pattern matching and modified them to make them print a different number each. For instance:
```
(
  "|"* @do_nothing
  (match_case) @prepend_spaced_softline @append_delimiter
  (#delimiter! "2")
)
```
and then one can run `topiary --input-file=match_1024.ml --skip-idempotence` and see that there are hundreds of 2's, so that the issue comes from this query.

**Comment by torhovland** [comment]
I have on occasion also misused `@append_delimiter` to debug which pattern is getting applied in a particular situation 😀

**Pull request merged**
