### PR TITLE
Website contents

### LINKED ISSUE #355: Put some content and styling on the web site at topiary.tweag.io
**Is your feature request related to a problem? Please describe.**
A very basic web site is deployed at topiary.tweag.io, but it needs some content and styling.

It doesn't need a lot, but this would probably be nice:

- A short introduction to Topiary.
- How to install and run.
- A prominent link to the playground.
- Link to GitHub.
- GitHub badges.
- Link to blog post.
- Link to Tweag.
- Link to Tree-sitter.
- Later: link to crate, and to various package repositories.

**Describe the solution you'd like**
A nice web page.

**Additional context**
See the following for inspiration:

- https://nickel-lang.org
- https://tree-sitter.github.io

### PR DESCRIPTION
**Pull request by torhovland**
Fixes #355.

- Simple Bootstrap design.
- Hero text and image.
- Getting started plus links.
- Badges.

### CODE REVIEW

**Review by Xophmeister — APPROVED** [review]
LGTM :+1:

This is subjective and not a blocker, but I'm not a huge fan of the hero image; it's quite low-contrast and lacks focus. However, it will do for now and we've used it before, in the blog post, so :+1:

---

**Edit** For example, I saw [this](https://bingwallpaper.anerg.com/detail/us/CyprusMaze) the other day, which I think really stands out. However, it's presumably copyright encumbered:

**Comment by torhovland** [comment]
> This is subjective and not a blocker, but I'm not a huge fan of the hero image; it's quite low-contrast and lacks focus. However, it will do for now and we've used it before, in the blog post, so

Sure, this is definitely a case of "better than nothing".

**Comment by torhovland** [comment]
> **Edit** For example, I saw [this](https://bingwallpaper.anerg.com/detail/us/CyprusMaze) the other day, which I think really stands out. However, it's presumably copyright encumbered:

Yeah, that's nice. Not sure about the licensing. Here's a similar one that can be bought:
https://www.alamy.com/maze-of-bushes-in-botanical-park-ayia-napa-cyprus-image343901704.html

**Comment by aspiwack** [comment]
I'd say that the website is good enough for now. We can have a discussion about graphic design later.

**Pull request merged**
