### PR TITLE
[perf] Store query matches locally to avoid running query twice

### PR DESCRIPTION
**Pull request by nbacquey**
Decreases the processing time of larger OCaml files from ~7s to ~1.6s

### CODE REVIEW

**Review by Xophmeister — APPROVED** [review]
Looks great :+1:

Not for this PR, but just thinking out aloud: Do any of the performance metrics show the time spent hashing? If it's a lot, maybe moving to a faster algorithm, rather than Rust's default with DoS-protection, would be worthwhile...

**Comment by nbacquey** [comment]
Right now, nothing seems to indicate we spend much time hashing. The most recent flame graph indicates that most of the time is spent applying the query, in the C bindings themselves
flamegraph

**Comment by aspiwack** [comment]
> from ~7s to ~1.6s

:exploding_head:

**Comment by torhovland** [comment]
And the best part: by not running something twice 😀

**Comment by aspiwack** [comment]
Dividing by 3 by doing 1/2 as much work. Pretty :sunglasses: .

**Pull request merged**
