### PR TITLE
Fix: open scope "function_definition" more often

### LINKED ISSUE #529: Idempotency error (and other peculiar behaviours) with `function` inside an `if-then-else` construct
**Describe the bug**

On:
```ocaml
let id = if true then Fun.id else function x -> x
```
Topiary produces an idempotency error, the first pass producing:
```ocaml
let id = if true then Fun.id else functionx -> x
```
which is not syntactically correct.

Notes:
- This also happens with more arguments to `function`, eg. `function x -> x | y -> y`.
- This also happens with a multiline `if-then-else`.
- This also happens with a multiline `function`, including with a newline between `function` and `x -> x`.
- This does not happen for `let id = function x -> x`.
- This does not happen for `let id = if true then Fun.id else function | x -> x` and the `|` remains, while it is removed from `let id = function | x -> x`.

**To Reproduce**

```
nix run github:tweag/topiary/cba1993 -- -l ocaml <<EOF
let id = if true then Fun.id else function x -> x
EOF
```
will produce:
```
[2023-06-22T18:13:51Z ERROR topiary] Parsing error between line 1, column 46 and line 1, column 47
```
while its `-s` counterpart will produce:
```
let id = if true then Fun.id else functionx -> x
```

### PR DESCRIPTION
**Pull request by nbacquey**
Closes #529
Modifies #536

### CODE REVIEW

**Comment by nbacquey** [comment]
Fun fact: I wanted to write
```
(
  _ @begin_scope
  .
  (function_expression
    "function" @append_spaced_scoped_softline
  ) @end_scope
  (#scope_id! "function_definition")
)
```
With `_` instead of `(_)`, to capture both named and non-named nodes, and get rid of the two cases above which open the `function_definition` scope.
Alas, the snippet above is not syntactically correct, for some reason?

**Review by torhovland — APPROVED** [review]

**Comment by torhovland** [comment]
Unfortunately, your "fun" fact is causing problems.

`(_)` is not capturing the `else` block, because it is unnamed. And `_` causes a query error, as you say. This actually works, but is not very general:

```scheme
(
  "else" @begin_scope
  .
  (function_expression
    "function" @append_spaced_scoped_softline
  ) @end_scope
  (#scope_id! "function_definition")
)
```

**Comment by torhovland** [comment]
This also doesn't work, and I'm not sure why:

```scheme
(
  (_) @begin_scope
  .
  (
    (function_expression
      "function" @append_spaced_scoped_softline
    ) @end_scope
  )
  (#scope_id! "function_definition")
)
```

**Comment by nbacquey** [comment]
I've thought about something: even if the following was a correct query, we shouldn't use it:
```
(
  _ @begin_scope
  .
  (function_expression
    "function" @append_spaced_scoped_softline
  ) @end_scope
  (#scope_id! "function_definition")
)
```
That's because we know `.` can skip anonymous nodes, so if we have something like `(let) "=" (function_expression)`, then `_ @begin_scope` would match on both `(let)` and `"="`, and the scope would be opened twice, in different places.

**Comment by torhovland** [comment]
Right, but both of them would also be closed. Wouldn't that be OK?

**Comment by nbacquey** [comment]
That would be okay-ish. Both scopes would be closed indeed, but weird thing could happen if there were matches that use the `function_definition` scope between `(let)` and `"="`, like a scoped newline, or worse, closing a previously opened scope.

**Pull request merged**
